steps:
  # - label: linux-steps
  #   command: 
  #     - node --version
  #     - yarn --version
  #     - bazel info
  #   plugins:
  #     - docker#v2.0.0:
  #         image: "angular/ngcontainer:0.7.0"
  #         workdir: "/src"
  #   agents:
  #     linux: true          
  - label: windows-steps
    command: "dir && not-a-binary"
    plugins:
      - docker#v2.0.0:
          image: "microsoft/dotnet:latest"
    agents:
      windows: true